baseURL = 'https://richardlyon.netlify.app/'
languageCode = 'en-GB'
title = 'Richard Lyon'
cleanDestinationDir = false
theme = 'equity'

[taxonomies]
subject = 'subjects'

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [['\[', '\]'], ['$$', '$$']], inline = [['\(', '\)']] }

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
