[[main]]
name = 'Writing'
pageRef = '/writing'
weight = 10

[[main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

# [[main]]
# name = 'Photography'
# pageRef = '/photos'
# weight = 30

[[main]]
name = 'Subjects'
pageRef = '/subjects'
weight = 40


[[main]]
name = 'About'
pageRef = '/about'
weight = 50

